## audit: run quality control checks
.PHONY: audit
audit:
	go mod vendor
	go mod tidy -v
	go fmt ./...
	go vet ./...
	go run honnef.co/go/tools/cmd/staticcheck@latest -checks=all,-ST1000,-U1000 ./...
	go test -race -vet=off ./...
	go mod verify