name: "Lint Code"

on:
  push:
    tags: [ "-v*" ]
    branches: [ "main" ]
  pull_request:

#permissions:
#  contents: read

jobs:
  ling:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.X

      - name: lint
        uses: golangci/golangci-lint-action@v3